Add Strapi v4 support
strapi/strapi-docker pull request #336
Opened 2022-05-24 11:15 UTC by pierreburgy

Add Strapi v4 support for the Strapi Docker image.

2022-05-27 08:59 UTC, bcdevlucas commented
If anyone is looking for an updated project I've created one here:
https://github.com/bluecollardev/strapi-launcher

- Supports Strapi v4 as well as older versions of Strapi (3x, 2x).
- Specify Strapi versions and Node.js versions when building images.
- Updated to use ES modules. As such this library requires Node.js >= 12.
- Uses commander instead of argv for CLI.

2022-06-15 16:16 UTC, Convly requested changes

2022-06-15 16:16 UTC, Convly commented on bin/constants.js
> +const NODE_VERSIONS = [12, 14];
14, 16 since v4.2.0

2022-06-15 16:17 UTC, Convly commented on bin/constants.js
> +const NODE_VERSIONS = [12, 14];
Although if we support v3 we still need 12, 14 :sweat_smile:

2023-03-02 09:43 UTC, closed without merging